create column table address_cleanse_runs (

--===============================================
-- [address_cleanse_runs]
--    - Metrics around cleansing runs
-- 
--  07.31.2017 - haupinzd - created
--===============================================

  run_id integer not null generated by default as identity (start with 1000 increment by 1)
  , start_ts timestamp default current_timestamp
  , end_ts timestamp
)
;
